{{- if or .Values.secrets.openaiApiKey .Values.secrets.geminiApiKey .Values.secrets.anthropicApiKey .Values.secrets.oakenApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-llm-keys
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- with .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.geminiApiKey }}
  GEMINI_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oakenApiKey }}
  OAKEN_API_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
