image:
  repository: ghcr.io/recuperarcontato4-prog/oaken-agent
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
